prasanthre@cloudshell:~ (ap-mumbai-1)$ oci container-instances container-instance list --all
Usage: oci container-instances container-instance list [OPTIONS]

Error: Missing option(s) --compartment-id.
prasanthre@cloudshell:~ (ap-mumbai-1)$ 
