name: Debug Container Instance Deletion

on:
  workflow_dispatch:

jobs:
  delete-container-instance:
    runs-on: ubuntu-latest
    env:
      OCI_CLI_PROFILE: ${{ secrets.OCI_CLI_PROFILE }}
      OCI_CLI_CONFIG: ~/.oci/config

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip jq
          pip3 install oci-cli

      - name: List Container Instances (Debug)
        run: |
          echo "Listing all container instances in compartment: ${{ secrets.OCI_COMPARTMENT_OCID }}"
          oci container-instances container-instance list \
            --compartment-id ${{ secrets.OCI_COMPARTMENT_OCID }} \
            --query "data[*].{Name:'display-name', ID:id}" \
            --output table

      - name: Get Instance OCID
        id: get-ocid
        run: |
          echo "Fetching OCID for container instance: icsapplication-v1.0.2"
          instance_ocid=$(oci container-instances container-instance list \
            --compartment-id ${{ secrets.OCI_COMPARTMENT_OCID }} \
            --display-name "icsapplication-v1.0.2" \
            --query "data[0].id" --raw-output)
          
          if [ -z "$instance_ocid" ]; then
            echo "No container instance found with the name 'icsapplication-v1.0.2'."
            exit 1
          fi

          echo "Instance OCID: $instance_ocid"
          echo "instance_ocid=$instance_ocid" >> $GITHUB_ENV

      - name: Delete Container Instance
        run: |
          echo "Deleting container instance with OCID: $instance_ocid"
          oci container-instances container-instance delete --container-instance-id "$instance_ocid" --force --wait-for-state DELETED

          echo "Container instance 'icsapplication-v1.0.2' successfully deleted."
