name: Build and Push Docker Image to OCI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.OCI_IMAGE_REPOSITORY }}:latest .

      - name: Authenticate to OCI and push image
        run: |
          echo ${{ secrets.OCI_PRIVATE_KEY }} | base64 --decode > oci_private_key.pem
          oci --region ${{ secrets.OCI_REGION }} session authenticate --key-file oci_private_key.pem \
              --tenancy-id ${{ secrets.OCI_TENANCY_OCID }} \
              --user-id ${{ secrets.OCI_USER_OCID }} \
              --fingerprint ${{ secrets.OCI_KEY_FINGERPRINT }}
          docker login -u ${{ secrets.OCI_USER_OCID }} -p "$(oci iam auth token create --region ${{ secrets.OCI_REGION }} --user-id ${{ secrets.OCI_USER_OCID }} --description 'GitHub Actions Token' --key-file oci_private_key.pem)" ${{ secrets.OCI_IMAGE_REPOSITORY }}
          docker push ${{ secrets.OCI_IMAGE_REPOSITORY }}:latest
